spring:
  application:
    name: zuul
  cloud:
    config:
      override-none: true    

server:
  port: 3001    

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka


zuul:
  routes:
    item-serive: /item-serive/**
    user-serive: /user-serive/**
    order-serive: /order-serive/**   
    

ribbon:
 MaxAutoRetries: 1  
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
     
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream  
  